apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aki-detection-state
  namespace: peninsula
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aki-detection
  namespace: peninsula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aki-detection
  template:
    metadata:
      labels:
        app: aki-detection
    spec:
      initContainers:
      - name: copy-hospital-history
        image: imperialswemlsspring2026.azurecr.io/coursework4-history
        volumeMounts:
          - mountPath: "/data"
            name: hospital-history
        resources:
          requests:
            memory: 64Mi
            cpu: 100m

      containers:
      - name: aki-detection
        image: imperialswemlsspring2026.azurecr.io/coursework4-peninsula:v1
        imagePullPolicy: Always

        command: ["python", "-u", "-m", "aki_service"]
        args: ["--history", "/data/history.csv", "--db", "/state/aki_service.db"]

        env:
        - name: MLLP_ADDRESS
          value: peninsula-simulator.coursework4:8440
        - name: PAGER_ADDRESS
          value: peninsula-simulator.coursework4:8441
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        - name: DB_PATH
          value: "/state/aki_service.db"

        volumeMounts:
          - mountPath: "/data"
            name: hospital-history
            readOnly: true
          - mountPath: "/state"
            name: aki-detection-state

        resources:
          requests:
            memory: 900Mi
            cpu: 500m

      volumes:
      - name: hospital-history
        emptyDir:
          sizeLimit: 50Mi
      - name: aki-detection-state
        persistentVolumeClaim:
          claimName: aki-detection-state
